"""
ASCII / Braille art with Pango markup colorization.
Shared between Niri widgets (cheatsheet, clock, etc.).

Usage:
    from ascii_art import load_flower
    label.set_use_markup(True)
    label.set_markup(load_flower())
"""

import html
import os

# Maps each art character to a color. The current flower (CenterBF.txt) was
# generated by an image-to-ASCII converter that picks denser glyphs for darker
# pixels, so a character->color map gives a natural depth gradient: sparse
# glyphs render pale, dense glyphs render saturated.
#
# Palette runs from very pale light-blue through to neon-blue/cyan.
# Any character not in this map (spaces, etc.) is left uncolored.
FLOWER_PALETTE = {
    '.': "#d6ecff",   # palest light blue   (lowest density)
    ':': "#a3d4ff",   # light blue
    '-': "#5fb0ff",   # medium-light blue
    '=': "#5fb0ff",   # medium-light blue   (same tier as '-')
    '+': "#2a8aff",   # bright blue
    '*': "#2a8aff",   # bright blue         (same tier as '+')
    '%': "#1f51ff",   # neon blue
    '#': "#1f51ff",   # neon blue           (same tier as '%')
    '@': "#00e1ff",   # neon cyan accent    (densest — flower center / bud)
}


def colorize(art, palette=None):
    """Wrap each character of `art` in a Pango <span> colored per `palette`.

    Characters not in the palette (spaces, etc.) are emitted uncolored.
    Consecutive characters with the same color are grouped into one span
    so the resulting markup stays small.
    """
    if palette is None:
        palette = FLOWER_PALETTE

    def flush(chunks, buf, color):
        if not buf:
            return
        text = html.escape(buf)
        if color is None:
            chunks.append(text)
        else:
            chunks.append(f'<span foreground="{color}">{text}</span>')

    out_lines = []
    for line in art.splitlines():
        chunks, buf, cur_color = [], "", None
        for ch in line:
            color = palette.get(ch)
            if color != cur_color:
                flush(chunks, buf, cur_color)
                buf = ""
                cur_color = color
            buf += ch
        flush(chunks, buf, cur_color)
        out_lines.append("".join(chunks))
    return "\n".join(out_lines)


def load_flower(path=None, palette=None):
    """Read the flower art file and return Pango markup.

    Defaults to CenterBF.txt in the same directory as this module.
    """
    if path is None:
        path = os.path.join(os.path.dirname(__file__), "CenterBF.txt")
    with open(path, encoding="utf-8") as f:
        return colorize(f.read(), palette)
